<?php // this is an autogenerated file - do not edit (created Mon, 03 Oct 2011 23:14:18 +0900)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'fluent\\event' => '/Event.php',
            'fluent\\logger\\baselogger' => '/Logger/BaseLogger.php',
            'fluent\\logger\\consolelogger' => '/Logger/ConsoleLogger.php',
            'fluent\\logger\\fluentlogger' => '/Logger/FluentLogger.php',
            'fluent\\logger\\httplogger' => '/Logger/HttpLogger.php',
            'fluent\\logger\\scribelogger' => '/Logger/ScribeLogger.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
